version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    depends_on:
      - frontend

  frontend:
    build: ./admin-frontend
    container_name: mern-frontend
    ports:
      - "3000:80"
